export const destinations = [
  {
    id: 1,
    name: "Kawasan Falls",
    description: "Famous multi-tiered waterfalls with turquoise water.",
    region: "Central Visayas",
    city: "Badian, Cebu",
    tags: ["nature", "adventure", "waterfalls"],
    popularity: 95,
    imageUrl: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86",
    activities: ["Canyoneering", "Swimming", "Bamboo Rafting"],
    bestTime: "January to May",
  },
  {
    id: 2,
    name: "Chocolate Hills",
    description: "Geological formation of at least 1,260 hills.",
    region: "Central Visayas",
    city: "Carmen, Bohol",
    tags: ["nature", "sightseeing", "history"],
    popularity: 90,
    imageUrl: "https://images.unsplash.com/photo-1590059530465-b7470f592393",
    activities: ["Viewpoint sightseeing", "ATV rides"],
    bestTime: "December to May",
  },
  {
    id: 3,
    name: "El Nido Lagoons",
    description: "Stunning limestone cliffs and crystal clear lagoons.",
    region: "Palawan",
    city: "El Nido",
    tags: ["beach", "island hopping", "nature"],
    popularity: 98,
    imageUrl: "https://images.unsplash.com/photo-1534951474654-88675cc52c92",
    activities: ["Island Hopping", "Kayaking", "Snorkeling"],
    bestTime: "November to May",
  },
  {
    id: 4,
    name: "Intramuros",
    description: "The historic walled city of Manila.",
    region: "Metro Manila",
    city: "Manila",
    tags: ["history", "culture", "sightseeing"],
    popularity: 85,
    imageUrl: "https://images.unsplash.com/photo-1597332348704-20b17849c719",
    activities: ["Walking tour", "Fort Santiago visit", "Kalesa ride"],
    bestTime: "Year-round",
  },
  {
    id: 5,
    name: "Banaue Rice Terraces",
    description: "2,000-year-old terraces carved into the mountains.",
    region: "Cordillera",
    city: "Banaue",
    tags: ["nature", "culture", "hiking"],
    popularity: 88,
    imageUrl: "https://images.unsplash.com/photo-1596409581971-8557d363d64c",
    activities: ["Trekking", "Cultural immersion", "Photography"],
    bestTime: "April to June; October to January",
  },
  {
    id: 6,
    name: "Magellan's Cross",
    description: "Christian cross planted by Portuguese and Spanish explorers.",
    region: "Central Visayas",
    city: "Cebu City",
    tags: ["history", "culture", "religion"],
    popularity: 80,
    imageUrl: "https://images.unsplash.com/photo-1620757277873-616335133643",
    activities: ["Sightseeing", "Prayer"],
    bestTime: "Year-round",
  },
  {
    id: 7,
    name: "White Beach",
    description: "World-famous powdery white sand beach.",
    region: "Western Visayas",
    city: "Boracay",
    tags: ["beach", "party", "relaxation", "luxury"],
    popularity: 99,
    imageUrl: "https://images.unsplash.com/photo-1506929562872-bb421503ef21",
    activities: ["Swimming", "Sunset watching", "Water sports", "Nightlife"],
    bestTime: "November to April",
  },
  {
    id: 8,
    name: "Rizal Park (Luneta)",
    description: "Large historic urban park dedicated to national hero José Rizal — great for strolling and people-watching.",
    region: "Metro Manila",
    city: "Manila",
    tags: ["history", "culture", "sightseeing", "family"],
    popularity: 86,
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    activities: ["Strolling", "Picnic", "Horse-drawn carriage rides", "Monument viewing"],
    bestTime: "November to April",
  },
  {
    id: 9,
    name: "National Museum Complex",
    description: "Collection of national museums (Fine Arts, Anthropology, Natural History) showcasing Philippine heritage and art.",
    region: "Metro Manila",
    city: "Manila",
    tags: ["museum", "history", "art", "culture"],
    popularity: 83,
    imageUrl: "https://images.unsplash.com/photo-1529101091764-c3526daf38fe",
    activities: ["Museum tours", "Special exhibitions", "Educational programs"],
    bestTime: "Year-round",
  },
  {
    id: 10,
    name: "Binondo (Chinatown) — Food Crawl",
    description: "One of the oldest Chinatowns in the world — a must for street-food hunters and heritage walks.",
    region: "Metro Manila",
    city: "Manila (Binondo)",
    tags: ["food", "history", "sightseeing"],
    popularity: 89,
    imageUrl: "https://images.unsplash.com/photo-1543332164-8f4e6f1d3d6a",
    activities: ["Food crawl", "Heritage walking tour", "Temple visits"],
    bestTime: "Year-round",
  },
  {
    id: 11,
    name: "SM Mall of Asia & Baywalk",
    description: "Massive seaside mall with baywalk promenade — shopping, family entertainment, and sunset views over Manila Bay.",
    region: "Metro Manila",
    city: "Pasay",
    tags: ["shopping", "family", "relaxation"],
    popularity: 90,
    imageUrl: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade",
    activities: ["Shopping", "Sunset baywalk", "IMAX/cinema", "Rides & family attractions"],
    bestTime: "Year-round",
  },
  {
    id: 12,
    name: "Bonifacio Global City (BGC) / The Fort",
    description: "Modern business & lifestyle district with high-end shopping, public art, parks, and lively dining/nightlife.",
    region: "Metro Manila",
    city: "Taguig",
    tags: ["shopping", "nightlife", "art", "luxury"],
    popularity: 92,
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
    activities: ["Dining", "Street art walks", "High-end shopping", "Nightlife"],
    bestTime: "Year-round",
  },
  {
    id: 13,
    name: "Ayala Museum & Greenbelt",
    description: "Makati’s cultural hub — history and contemporary art museum right beside upscale malls and a serene park.",
    region: "Metro Manila",
    city: "Makati",
    tags: ["museum", "art", "shopping", "culture"],
    popularity: 85,
    imageUrl: "https://images.unsplash.com/photo-1509099836639-18ba2a8b4a0b",
    activities: ["Museum visit", "Gallery tours", "Dining at Greenbelt", "Shopping"],
    bestTime: "Year-round",
  },
  {
    id: 14,
    name: "Cultural Center of the Philippines (CCP)",
    description: "National center for the performing arts — concerts, ballet, theater, and cultural festivals take place here.",
    region: "Metro Manila",
    city: "Pasay",
    tags: ["culture", "art", "family"],
    popularity: 78,
    imageUrl: "https://images.unsplash.com/photo-1508973376-0b5a5b9f5b77",
    activities: ["Performing arts", "Concerts", "Cultural shows", "Festivals"],
    bestTime: "Year-round (check event schedule)",
  },
  {
    id: 15,
    name: "Quiapo Church & Markets",
    description: "Iconic pilgrimage church next to bustling markets — known for religious traditions, charms, and lively street commerce.",
    region: "Metro Manila",
    city: "Manila (Quiapo)",
    tags: ["history", "culture", "shopping", "religion"],
    popularity: 75,
    imageUrl: "https://images.unsplash.com/photo-1543269865-cbf427effbad",
    activities: ["Pilgrimage", "Market shopping", "Street food", "Antique hunting"],
    bestTime: "Year-round (busiest on Fridays and religious holidays)",
  }
];

export const regions = [
  { id: 1, name: "Central Visayas", code: "CV", description: "Home to Cebu, Bohol, and Siquijor.", imageUrl: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86" },
  { id: 2, name: "Palawan", code: "PLW", description: "The last frontier, famous for El Nido and Coron.", imageUrl: "https://images.unsplash.com/photo-1534951474654-88675cc52c92" },
  { id: 3, name: "Metro Manila", code: "NCR", description: "The bustling capital region.", imageUrl: "https://images.unsplash.com/photo-1582269584285-b4618a8f1b62" },
  { id: 4, name: "Cordillera", code: "CAR", description: "Mountainous region famous for rice terraces.", imageUrl: "https://images.unsplash.com/photo-1596409581971-8557d363d64c" },
];

export const tags = [
  { id: 1, name: "beach", category: "Activity" },
  { id: 2, name: "food", category: "Activity" },
  { id: 3, name: "history", category: "Activity" },
  { id: 4, name: "nature", category: "Activity" },
  { id: 5, name: "adventure", category: "Vibe" },
  { id: 6, name: "relaxation", category: "Vibe" },
  { id: 7, name: "budget", category: "Budget" },
  { id: 8, name: "luxury", category: "Budget" },
];
