export const destinations = [
  {
    id: 1,
    name: "Kawasan Falls",
    description: "Famous multi-tiered waterfalls with turquoise water.",
    region: "Central Visayas",
    city: "Badian, Cebu",
    tags: ["nature", "adventure", "waterfalls"],
    popularity: 95,
    imageUrl: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86",
    activities: ["Canyoneering", "Swimming", "Bamboo Rafting"],
    bestTime: "January to May",
  },
  {
    id: 2,
    name: "Chocolate Hills",
    description: "Geological formation of at least 1,260 hills.",
    region: "Central Visayas",
    city: "Carmen, Bohol",
    tags: ["nature", "sightseeing", "history"],
    popularity: 90,
    imageUrl: "https://images.unsplash.com/photo-1590059530465-b7470f592393",
    activities: ["Viewpoint sightseeing", "ATV rides"],
    bestTime: "December to May",
  },
  {
    id: 3,
    name: "El Nido Lagoons",
    description: "Stunning limestone cliffs and crystal clear lagoons.",
    region: "Palawan",
    city: "El Nido",
    tags: ["beach", "island hopping", "nature"],
    popularity: 98,
    imageUrl: "https://images.unsplash.com/photo-1534951474654-88675cc52c92",
    activities: ["Island Hopping", "Kayaking", "Snorkeling"],
    bestTime: "November to May",
  },
  {
    id: 4,
    name: "Intramuros",
    description: "The historic walled city of Manila.",
    region: "Metro Manila",
    city: "Manila",
    tags: ["history", "culture", "sightseeing"],
    popularity: 85,
    imageUrl: "https://images.unsplash.com/photo-1597332348704-20b17849c719",
    activities: ["Walking tour", "Fort Santiago visit", "Kalesa ride"],
    bestTime: "Year-round",
  },
  {
    id: 5,
    name: "Banaue Rice Terraces",
    description: "2,000-year-old terraces carved into the mountains.",
    region: "Cordillera",
    city: "Banaue",
    tags: ["nature", "culture", "hiking"],
    popularity: 88,
    imageUrl: "https://images.unsplash.com/photo-1596409581971-8557d363d64c",
    activities: ["Trekking", "Cultural immersion", "Photography"],
    bestTime: "April to June; October to January",
  },
  {
    id: 6,
    name: "Magellan's Cross",
    description: "Christian cross planted by Portuguese and Spanish explorers.",
    region: "Central Visayas",
    city: "Cebu City",
    tags: ["history", "culture", "religion"],
    popularity: 80,
    imageUrl: "https://images.unsplash.com/photo-1620757277873-616335133643",
    activities: ["Sightseeing", "Prayer"],
    bestTime: "Year-round",
  },
  {
    id: 7,
    name: "White Beach",
    description: "World-famous powdery white sand beach.",
    region: "Western Visayas",
    city: "Boracay",
    tags: ["beach", "party", "relaxation", "luxury"],
    popularity: 99,
    imageUrl: "https://images.unsplash.com/photo-1506929562872-bb421503ef21",
    activities: ["Swimming", "Sunset watching", "Water sports", "Nightlife"],
    bestTime: "November to April",
  }
];

export const regions = [
  { id: 1, name: "Central Visayas", code: "CV", description: "Home to Cebu, Bohol, and Siquijor.", imageUrl: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86" },
  { id: 2, name: "Palawan", code: "PLW", description: "The last frontier, famous for El Nido and Coron.", imageUrl: "https://images.unsplash.com/photo-1534951474654-88675cc52c92" },
  { id: 3, name: "Metro Manila", code: "NCR", description: "The bustling capital region.", imageUrl: "https://images.unsplash.com/photo-1582269584285-b4618a8f1b62" },
  { id: 4, name: "Cordillera", code: "CAR", description: "Mountainous region famous for rice terraces.", imageUrl: "https://images.unsplash.com/photo-1596409581971-8557d363d64c" },
];

export const tags = [
  { id: 1, name: "beach", category: "Activity" },
  { id: 2, name: "food", category: "Activity" },
  { id: 3, name: "history", category: "Activity" },
  { id: 4, name: "nature", category: "Activity" },
  { id: 5, name: "adventure", category: "Vibe" },
  { id: 6, name: "relaxation", category: "Vibe" },
  { id: 7, name: "budget", category: "Budget" },
  { id: 8, name: "luxury", category: "Budget" },
];
